name: Continuous Translation

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: yunwei37/OpenAI-Continuous-Translator@master
        with:
          git_repo_url: https://github.com/appcypher/awesome-wasm-langs
          api_key: ${{ secrets.OPENAI_API_KEY }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: .
    - name: move and commit
      run: |
          rm repo-i18n-private/local_repo/.git
          mv -R repo-i18n-private/local_repo .
