name: Continuous Translation

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: yunwei37/OpenAI-Continuous-Translator@master
      with:
          git_repo_url: https://github.com/dair-ai/Prompt-Engineering-Guide
          api_key: ${{ secrets.OPENAI_API_KEY }}
          file_types: "md,mdx"
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: .
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
